author: Bruce
dbType: mysql
dbUrl: "jdbc:mysql://localhost:3306/mybatis_plus?characterEncoding=utf8&serverTimezone=GMT%2B8"
dbDriverName: "com.mysql.cj.jdbc.Driver"
dbUsername: root
dbPassword: root

parentPackage: com.bruce.mp
projectName: mp-test
#prefix: demo
includes: ["demo_mybatis_test"]

#outputDir:
#usebtl: true
#usevm: true
useftl: true